print('номер рейса:')
flight_num = input()
print('название авиакомпании (на русском языке):')
airline_rus = input()
print('название авиакомпании (на английском языке):')
airline_eng = input()
print('город прилета (на русском языке)')
city_rus = input()
print('город прилета (на английском языке)')
city_eng = input()
print('Заканчивается посадка на рейс', flight_num, airline_rus, 'до', city_rus)
print('This is the final boarding call for', airline_eng, flight_num, 'to', city_eng)